#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : minetest
Version  : 5.4.1
Release  : 40
URL      : https://github.com/minetest/minetest/archive/5.4.1/minetest-5.4.1.tar.gz
Source0  : https://github.com/minetest/minetest/archive/5.4.1/minetest-5.4.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 CC-BY-SA-3.0 LGPL-2.1+ MIT
Requires: minetest-bin = %{version}-%{release}
Requires: minetest-data = %{version}-%{release}
Requires: minetest-license = %{version}-%{release}
Requires: minetest-locales = %{version}-%{release}
Requires: minetest-man = %{version}-%{release}
BuildRequires : LuaJIT-dev
BuildRequires : buildreq-cmake
BuildRequires : bzip2-dev
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : gmp-dev
BuildRequires : irrlicht-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libogg-dev
BuildRequires : libpng-dev
BuildRequires : libspatialindex-dev
BuildRequires : libvorbis-dev
BuildRequires : lua-dev
BuildRequires : mesa-dev
BuildRequires : ncurses-dev
BuildRequires : openal-soft-dev
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(x11)
BuildRequires : postgresql-dev
BuildRequires : sqlite-autoconf-dev
BuildRequires : zlib-dev
Patch1: 0001-Fix-build-newer-versions-of-GCC.patch

%description
Minetest
========
![Build Status](https://github.com/minetest/minetest/workflows/build/badge.svg)
[![Translation status](https://hosted.weblate.org/widgets/minetest/-/svg-badge.svg)](https://hosted.weblate.org/engage/minetest/?utm_source=widget)
[![License](https://img.shields.io/badge/license-LGPLv2.1%2B-blue.svg)](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html)

%package bin
Summary: bin components for the minetest package.
Group: Binaries
Requires: minetest-data = %{version}-%{release}
Requires: minetest-license = %{version}-%{release}

%description bin
bin components for the minetest package.


%package data
Summary: data components for the minetest package.
Group: Data

%description data
data components for the minetest package.


%package doc
Summary: doc components for the minetest package.
Group: Documentation
Requires: minetest-man = %{version}-%{release}

%description doc
doc components for the minetest package.


%package extras
Summary: extras components for the minetest package.
Group: Default

%description extras
extras components for the minetest package.


%package license
Summary: license components for the minetest package.
Group: Default

%description license
license components for the minetest package.


%package locales
Summary: locales components for the minetest package.
Group: Default

%description locales
locales components for the minetest package.


%package man
Summary: man components for the minetest package.
Group: Default

%description man
man components for the minetest package.


%prep
%setup -q -n minetest-5.4.1
cd %{_builddir}/minetest-5.4.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1633041644
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DBUILD_CLIENT=1 \
-DBUILD_SERVER=1 \
-DENABLE_FREETYPE=1 \
-DBUILD_SHARED_LIBS=0
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1633041644
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/minetest
cp %{_builddir}/minetest-5.4.1/fonts/Arimo-LICENSE.txt %{buildroot}/usr/share/package-licenses/minetest/b1b13828a3a2be603b24a38d3948c7811d85f851
cp %{_builddir}/minetest-5.4.1/fonts/Cousine-LICENSE.txt %{buildroot}/usr/share/package-licenses/minetest/2b1b42e96714bc36f7bee9210a5e69e2586f7ee3
cp %{_builddir}/minetest-5.4.1/fonts/DroidSansFallbackFull-LICENSE.txt %{buildroot}/usr/share/package-licenses/minetest/b6c8486ea0f9b01549a4a9fd19216d6e8480f8d6
cp %{_builddir}/minetest-5.4.1/games/devtest/mods/testformspec/LICENSE.txt %{buildroot}/usr/share/package-licenses/minetest/109a1b93b80352920797150a7f7adf4cf70ef40e
cp %{_builddir}/minetest-5.4.1/lib/lua/COPYRIGHT %{buildroot}/usr/share/package-licenses/minetest/a6efc4d11f332f4843bc25b557c6bf3e5ef51458
pushd clr-build
%make_install
popd
%find_lang minetest

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/minetest

%files data
%defattr(-,root,root,-)
/usr/share/applications/net.minetest.minetest.desktop
/usr/share/icons/hicolor/128x128/apps/minetest.png
/usr/share/icons/hicolor/scalable/apps/minetest.svg
/usr/share/metainfo/net.minetest.minetest.appdata.xml
/usr/share/minetest/builtin/common/tests/misc_helpers_spec.lua
/usr/share/minetest/builtin/common/tests/serialize_spec.lua
/usr/share/minetest/builtin/common/tests/vector_spec.lua
/usr/share/minetest/builtin/mainmenu/async_event.lua
/usr/share/minetest/builtin/mainmenu/serverlistmgr.lua
/usr/share/minetest/builtin/mainmenu/tests/favorites_wellformed.txt
/usr/share/minetest/builtin/mainmenu/tests/serverlistmgr_spec.lua
/usr/share/minetest/client/shaders/3d_interlaced_merge/opengl_fragment.glsl
/usr/share/minetest/client/shaders/3d_interlaced_merge/opengl_vertex.glsl
/usr/share/minetest/client/shaders/default_shader/opengl_fragment.glsl
/usr/share/minetest/client/shaders/default_shader/opengl_vertex.glsl
/usr/share/minetest/client/shaders/minimap_shader/opengl_fragment.glsl
/usr/share/minetest/client/shaders/minimap_shader/opengl_vertex.glsl
/usr/share/minetest/client/shaders/nodes_shader/opengl_fragment.glsl
/usr/share/minetest/client/shaders/nodes_shader/opengl_vertex.glsl
/usr/share/minetest/client/shaders/object_shader/opengl_fragment.glsl
/usr/share/minetest/client/shaders/object_shader/opengl_vertex.glsl
/usr/share/minetest/client/shaders/selection_shader/opengl_fragment.glsl
/usr/share/minetest/client/shaders/selection_shader/opengl_vertex.glsl
/usr/share/minetest/client/shaders/stars_shader/opengl_fragment.glsl
/usr/share/minetest/client/shaders/stars_shader/opengl_vertex.glsl
/usr/share/minetest/fonts/Arimo-Bold.ttf
/usr/share/minetest/fonts/Arimo-BoldItalic.ttf
/usr/share/minetest/fonts/Arimo-Italic.ttf
/usr/share/minetest/fonts/Arimo-LICENSE.txt
/usr/share/minetest/fonts/Arimo-Regular.ttf
/usr/share/minetest/fonts/Cousine-Bold.ttf
/usr/share/minetest/fonts/Cousine-BoldItalic.ttf
/usr/share/minetest/fonts/Cousine-Italic.ttf
/usr/share/minetest/fonts/Cousine-LICENSE.txt
/usr/share/minetest/fonts/Cousine-Regular.ttf
/usr/share/minetest/fonts/DroidSansFallbackFull-LICENSE.txt
/usr/share/minetest/fonts/DroidSansFallbackFull.ttf
/usr/share/minetest/fonts/mono_dejavu_sans_10.xml
/usr/share/minetest/fonts/mono_dejavu_sans_100.png
/usr/share/minetest/fonts/mono_dejavu_sans_11.xml
/usr/share/minetest/fonts/mono_dejavu_sans_110.png
/usr/share/minetest/fonts/mono_dejavu_sans_12.xml
/usr/share/minetest/fonts/mono_dejavu_sans_120.png
/usr/share/minetest/fonts/mono_dejavu_sans_14.xml
/usr/share/minetest/fonts/mono_dejavu_sans_140.png
/usr/share/minetest/fonts/mono_dejavu_sans_16.xml
/usr/share/minetest/fonts/mono_dejavu_sans_160.png
/usr/share/minetest/fonts/mono_dejavu_sans_18.xml
/usr/share/minetest/fonts/mono_dejavu_sans_180.png
/usr/share/minetest/fonts/mono_dejavu_sans_20.xml
/usr/share/minetest/fonts/mono_dejavu_sans_200.png
/usr/share/minetest/fonts/mono_dejavu_sans_22.xml
/usr/share/minetest/fonts/mono_dejavu_sans_220.png
/usr/share/minetest/fonts/mono_dejavu_sans_24.xml
/usr/share/minetest/fonts/mono_dejavu_sans_240.png
/usr/share/minetest/fonts/mono_dejavu_sans_26.xml
/usr/share/minetest/fonts/mono_dejavu_sans_260.png
/usr/share/minetest/fonts/mono_dejavu_sans_28.xml
/usr/share/minetest/fonts/mono_dejavu_sans_280.png
/usr/share/minetest/fonts/mono_dejavu_sans_4.xml
/usr/share/minetest/fonts/mono_dejavu_sans_40.png
/usr/share/minetest/fonts/mono_dejavu_sans_6.xml
/usr/share/minetest/fonts/mono_dejavu_sans_60.png
/usr/share/minetest/fonts/mono_dejavu_sans_8.xml
/usr/share/minetest/fonts/mono_dejavu_sans_80.png
/usr/share/minetest/fonts/mono_dejavu_sans_9.xml
/usr/share/minetest/fonts/mono_dejavu_sans_90.png
/usr/share/minetest/games/devtest/LICENSE.txt
/usr/share/minetest/games/devtest/README.md
/usr/share/minetest/games/devtest/game.conf
/usr/share/minetest/games/devtest/menu/background.png
/usr/share/minetest/games/devtest/menu/header.png
/usr/share/minetest/games/devtest/menu/icon.png
/usr/share/minetest/games/devtest/mods/basenodes/init.lua
/usr/share/minetest/games/devtest/mods/basenodes/mod.conf
/usr/share/minetest/games/devtest/mods/basenodes/textures/basenodes_dirt_with_grass_bottom.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/basenodes_dirt_with_snow.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/basenodes_dirt_with_snow_bottom.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/basenodes_snow_sheet.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_apple.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_cobble.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_desert_sand.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_desert_stone.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_dirt.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_grass.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_gravel.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_ice.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_junglegrass.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_jungleleaves.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_jungletree.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_jungletree_top.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_lava.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_lava_flowing.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_leaves.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_mossycobble.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_pine_needles.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_pine_tree.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_pine_tree_top.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_river_water.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_river_water_flowing.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_sand.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_snow.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_snow_side.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_stone.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_tree.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_tree_top.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_water.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/default_water_flowing.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/dirt_with_grass/default_grass.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/dirt_with_grass/default_grass_side.png
/usr/share/minetest/games/devtest/mods/basenodes/textures/info.txt
/usr/share/minetest/games/devtest/mods/basetools/init.lua
/usr/share/minetest/games/devtest/mods/basetools/mod.conf
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_dirtpick.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_firesword.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_icesword.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_mesepick.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_steelaxe.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_steeldagger.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_steelpick.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_steelpick_l1.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_steelpick_l2.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_steelshears.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_steelshovel.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_steelsword.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_stoneaxe.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_stonepick.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_stoneshears.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_stoneshovel.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_stonesword.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_woodaxe.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_woodpick.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_woodshears.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_woodshovel.png
/usr/share/minetest/games/devtest/mods/basetools/textures/basetools_woodsword.png
/usr/share/minetest/games/devtest/mods/bucket/init.lua
/usr/share/minetest/games/devtest/mods/bucket/mod.conf
/usr/share/minetest/games/devtest/mods/bucket/textures/bucket.png
/usr/share/minetest/games/devtest/mods/bucket/textures/bucket_lava.png
/usr/share/minetest/games/devtest/mods/bucket/textures/bucket_water.png
/usr/share/minetest/games/devtest/mods/chest/init.lua
/usr/share/minetest/games/devtest/mods/chest/mod.conf
/usr/share/minetest/games/devtest/mods/chest/textures/chest_chest.png
/usr/share/minetest/games/devtest/mods/chest_of_everything/init.lua
/usr/share/minetest/games/devtest/mods/chest_of_everything/mod.conf
/usr/share/minetest/games/devtest/mods/chest_of_everything/textures/chest_of_everything_chest.png
/usr/share/minetest/games/devtest/mods/dignodes/init.lua
/usr/share/minetest/games/devtest/mods/dignodes/mod.conf
/usr/share/minetest/games/devtest/mods/dignodes/textures/dignodes_choppy.png
/usr/share/minetest/games/devtest/mods/dignodes/textures/dignodes_cracky.png
/usr/share/minetest/games/devtest/mods/dignodes/textures/dignodes_crumbly.png
/usr/share/minetest/games/devtest/mods/dignodes/textures/dignodes_dig_immediate.png
/usr/share/minetest/games/devtest/mods/dignodes/textures/dignodes_none.png
/usr/share/minetest/games/devtest/mods/dignodes/textures/dignodes_rating1.png
/usr/share/minetest/games/devtest/mods/dignodes/textures/dignodes_rating2.png
/usr/share/minetest/games/devtest/mods/dignodes/textures/dignodes_rating3.png
/usr/share/minetest/games/devtest/mods/experimental/commands.lua
/usr/share/minetest/games/devtest/mods/experimental/detached.lua
/usr/share/minetest/games/devtest/mods/experimental/init.lua
/usr/share/minetest/games/devtest/mods/experimental/items.lua
/usr/share/minetest/games/devtest/mods/experimental/mod.conf
/usr/share/minetest/games/devtest/mods/experimental/textures/experimental_callback_node.png
/usr/share/minetest/games/devtest/mods/experimental/textures/experimental_particle_sheet.png
/usr/share/minetest/games/devtest/mods/experimental/textures/experimental_particle_vertical.png
/usr/share/minetest/games/devtest/mods/experimental/textures/experimental_tester_tool_1.png
/usr/share/minetest/games/devtest/mods/give_initial_stuff/init.lua
/usr/share/minetest/games/devtest/mods/give_initial_stuff/mod.conf
/usr/share/minetest/games/devtest/mods/initial_message/init.lua
/usr/share/minetest/games/devtest/mods/initial_message/mod.conf
/usr/share/minetest/games/devtest/mods/mapgen/init.lua
/usr/share/minetest/games/devtest/mods/mapgen/mod.conf
/usr/share/minetest/games/devtest/mods/modchannels/init.lua
/usr/share/minetest/games/devtest/mods/modchannels/mod.conf
/usr/share/minetest/games/devtest/mods/soundstuff/init.lua
/usr/share/minetest/games/devtest/mods/soundstuff/mod.conf
/usr/share/minetest/games/devtest/mods/soundstuff/sounds/soundstuff_mono.ogg
/usr/share/minetest/games/devtest/mods/soundstuff/textures/soundstuff_eat.png
/usr/share/minetest/games/devtest/mods/soundstuff/textures/soundstuff_node_blank.png
/usr/share/minetest/games/devtest/mods/soundstuff/textures/soundstuff_node_climbable.png
/usr/share/minetest/games/devtest/mods/soundstuff/textures/soundstuff_node_dig.png
/usr/share/minetest/games/devtest/mods/soundstuff/textures/soundstuff_node_dug.png
/usr/share/minetest/games/devtest/mods/soundstuff/textures/soundstuff_node_fall.png
/usr/share/minetest/games/devtest/mods/soundstuff/textures/soundstuff_node_footstep.png
/usr/share/minetest/games/devtest/mods/soundstuff/textures/soundstuff_node_place.png
/usr/share/minetest/games/devtest/mods/soundstuff/textures/soundstuff_node_place_failed.png
/usr/share/minetest/games/devtest/mods/soundstuff/textures/soundstuff_node_sound.png
/usr/share/minetest/games/devtest/mods/stairs/init.lua
/usr/share/minetest/games/devtest/mods/stairs/mod.conf
/usr/share/minetest/games/devtest/mods/testentities/armor.lua
/usr/share/minetest/games/devtest/mods/testentities/callbacks.lua
/usr/share/minetest/games/devtest/mods/testentities/init.lua
/usr/share/minetest/games/devtest/mods/testentities/mod.conf
/usr/share/minetest/games/devtest/mods/testentities/textures/testentities_armorball.png
/usr/share/minetest/games/devtest/mods/testentities/textures/testentities_callback.png
/usr/share/minetest/games/devtest/mods/testentities/textures/testentities_callback_step.png
/usr/share/minetest/games/devtest/mods/testentities/textures/testentities_cube1.png
/usr/share/minetest/games/devtest/mods/testentities/textures/testentities_cube2.png
/usr/share/minetest/games/devtest/mods/testentities/textures/testentities_cube3.png
/usr/share/minetest/games/devtest/mods/testentities/textures/testentities_cube4.png
/usr/share/minetest/games/devtest/mods/testentities/textures/testentities_cube5.png
/usr/share/minetest/games/devtest/mods/testentities/textures/testentities_cube6.png
/usr/share/minetest/games/devtest/mods/testentities/textures/testentities_dungeon_master.png
/usr/share/minetest/games/devtest/mods/testentities/textures/testentities_sprite.png
/usr/share/minetest/games/devtest/mods/testentities/textures/testentities_upright_sprite1.png
/usr/share/minetest/games/devtest/mods/testentities/textures/testentities_upright_sprite2.png
/usr/share/minetest/games/devtest/mods/testentities/visuals.lua
/usr/share/minetest/games/devtest/mods/testfood/init.lua
/usr/share/minetest/games/devtest/mods/testfood/mod.conf
/usr/share/minetest/games/devtest/mods/testfood/textures/testfood_bad.png
/usr/share/minetest/games/devtest/mods/testfood/textures/testfood_bad2.png
/usr/share/minetest/games/devtest/mods/testfood/textures/testfood_good.png
/usr/share/minetest/games/devtest/mods/testfood/textures/testfood_good2.png
/usr/share/minetest/games/devtest/mods/testfood/textures/testfood_replace.png
/usr/share/minetest/games/devtest/mods/testformspec/LICENSE.txt
/usr/share/minetest/games/devtest/mods/testformspec/callbacks.lua
/usr/share/minetest/games/devtest/mods/testformspec/dummy_items.lua
/usr/share/minetest/games/devtest/mods/testformspec/formspec.lua
/usr/share/minetest/games/devtest/mods/testformspec/init.lua
/usr/share/minetest/games/devtest/mods/testformspec/mod.conf
/usr/share/minetest/games/devtest/mods/testformspec/models/testformspec_character.b3d
/usr/share/minetest/games/devtest/mods/testformspec/models/testformspec_chest.obj
/usr/share/minetest/games/devtest/mods/testformspec/textures/default_chest_front.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/default_chest_inside.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/default_chest_side.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/default_chest_top.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_animation.jpg
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_animation.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_bg.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_bg_9slice.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_bg_9slice_hovered.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_bg_9slice_pressed.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_bg_hovered.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_bg_pressed.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_button_image.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_character.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_hovered.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_item.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_node.png
/usr/share/minetest/games/devtest/mods/testformspec/textures/testformspec_pressed.png
/usr/share/minetest/games/devtest/mods/testnodes/README.md
/usr/share/minetest/games/devtest/mods/testnodes/drawtypes.lua
/usr/share/minetest/games/devtest/mods/testnodes/init.lua
/usr/share/minetest/games/devtest/mods/testnodes/light.lua
/usr/share/minetest/games/devtest/mods/testnodes/liquids.lua
/usr/share/minetest/games/devtest/mods/testnodes/meshes.lua
/usr/share/minetest/games/devtest/mods/testnodes/mod.conf
/usr/share/minetest/games/devtest/mods/testnodes/models/testnodes_ocorner.obj
/usr/share/minetest/games/devtest/mods/testnodes/models/testnodes_pyramid.obj
/usr/share/minetest/games/devtest/mods/testnodes/nodeboxes.lua
/usr/share/minetest/games/devtest/mods/testnodes/param2.lua
/usr/share/minetest/games/devtest/mods/testnodes/properties.lua
/usr/share/minetest/games/devtest/mods/testnodes/settingtypes.txt
/usr/share/minetest/games/devtest/mods/testnodes/textures.lua
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_1.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_1g.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_1w.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_1wg.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_2.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_2g.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_2w.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_2wg.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_3.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_3g.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_3w.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_3wg.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_4.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_4g.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_4w.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_4wg.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_5.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_5g.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_5w.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_5wg.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_6.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_6g.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_6w.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_6wg.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_airlike.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_allfaces.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_allfaces_optional.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_alpha.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_alpha128.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_alpha191.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_alpha64.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_anim.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_attached_bottom.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_attached_side.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_attached_top.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_attachedw_bottom.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_attachedw_side.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_attachedw_top.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_bouncy.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_buildable_to.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_climbable_nojump_side.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_climbable_side.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_damage.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_damage_neg.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_drowning.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_fall_damage_minus.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_fall_damage_plus.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_fencelike.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_firelike.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_glasslike.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_glasslike_detail.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_glasslike_framed.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_glasslike_framed2.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_glasslike_framed_optional.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_glasslikeliquid.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_1.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_10.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_11.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_12.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_13.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_14.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_2.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_3.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_4.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_5.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_6.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_7.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_8.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_light_9.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_line_crossing.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_line_curved.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_line_straight.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_line_t_junction.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquid.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidflowing.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidflowing_r0.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidflowing_r1.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidflowing_r2.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidflowing_r3.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidflowing_r4.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidflowing_r5.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidflowing_r6.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidflowing_r7.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidflowing_r8.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidsource.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidsource_r0.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidsource_r1.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidsource_r2.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidsource_r3.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidsource_r4.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidsource_r5.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidsource_r6.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidsource_r7.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_liquidsource_r8.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_mesh_stripes.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_mesh_stripes2.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_mesh_stripes3.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_mesh_stripes4.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_node.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_node_falling.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_nodebox.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_nojump_side.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_nojump_top.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_normal.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_normal1.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_normal2.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_normal3.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_normal4.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_normal5.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_normal6.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_palette_facedir.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_palette_full.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_palette_wallmounted.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_degrotate.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_leveled.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_meshoptions.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_rooted.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_rooted_base.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_rooted_base_side_degrotate.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_rooted_base_side_leveled.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_rooted_base_side_meshoptions.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_rooted_base_side_waving.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_rooted_degrotate.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_rooted_leveled.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_rooted_meshoptions.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_rooted_waving.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_plantlike_waving.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_rail2_crossing.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_rail2_curved.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_rail2_straight.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_rail2_t_junction.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_rail_crossing.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_rail_curved.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_rail_straight.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_rail_t_junction.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_signlike.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_slippery.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_street_crossing.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_street_curved.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_street_straight.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_street_t_junction.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_sunlight_filter.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_torchlike_ceiling.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_torchlike_floor.png
/usr/share/minetest/games/devtest/mods/testnodes/textures/testnodes_torchlike_wall.png
/usr/share/minetest/games/devtest/mods/testpathfinder/README.md
/usr/share/minetest/games/devtest/mods/testpathfinder/init.lua
/usr/share/minetest/games/devtest/mods/testpathfinder/mod.conf
/usr/share/minetest/games/devtest/mods/testpathfinder/textures/testpathfinder_testpathfinder.png
/usr/share/minetest/games/devtest/mods/testpathfinder/textures/testpathfinder_waypoint.png
/usr/share/minetest/games/devtest/mods/testpathfinder/textures/testpathfinder_waypoint_end.png
/usr/share/minetest/games/devtest/mods/testpathfinder/textures/testpathfinder_waypoint_start.png
/usr/share/minetest/games/devtest/mods/testtools/README.md
/usr/share/minetest/games/devtest/mods/testtools/init.lua
/usr/share/minetest/games/devtest/mods/testtools/light.lua
/usr/share/minetest/games/devtest/mods/testtools/mod.conf
/usr/share/minetest/games/devtest/mods/testtools/textures/testtools_entity_rotator.png
/usr/share/minetest/games/devtest/mods/testtools/textures/testtools_entity_scaler.png
/usr/share/minetest/games/devtest/mods/testtools/textures/testtools_entity_spawner.png
/usr/share/minetest/games/devtest/mods/testtools/textures/testtools_falling_node_tool.png
/usr/share/minetest/games/devtest/mods/testtools/textures/testtools_lighttool.png
/usr/share/minetest/games/devtest/mods/testtools/textures/testtools_node_setter.png
/usr/share/minetest/games/devtest/mods/testtools/textures/testtools_object_attacher.png
/usr/share/minetest/games/devtest/mods/testtools/textures/testtools_object_editor.png
/usr/share/minetest/games/devtest/mods/testtools/textures/testtools_object_mover.png
/usr/share/minetest/games/devtest/mods/testtools/textures/testtools_param2tool.png
/usr/share/minetest/games/devtest/mods/testtools/textures/testtools_remover.png
/usr/share/minetest/games/devtest/mods/tiled/init.lua
/usr/share/minetest/games/devtest/mods/tiled/mod.conf
/usr/share/minetest/games/devtest/mods/tiled/textures/tiled_tiled.png
/usr/share/minetest/games/devtest/mods/unittests/crafting.lua
/usr/share/minetest/games/devtest/mods/unittests/crafting_prepare.lua
/usr/share/minetest/games/devtest/mods/unittests/init.lua
/usr/share/minetest/games/devtest/mods/unittests/itemdescription.lua
/usr/share/minetest/games/devtest/mods/unittests/mod.conf
/usr/share/minetest/games/devtest/mods/unittests/player.lua
/usr/share/minetest/games/devtest/mods/unittests/random.lua
/usr/share/minetest/games/devtest/mods/unittests/textures/default_dirt.png
/usr/share/minetest/games/devtest/mods/unittests/textures/unittests_coal_lump.png
/usr/share/minetest/games/devtest/mods/unittests/textures/unittests_iron_lump.png
/usr/share/minetest/games/devtest/mods/unittests/textures/unittests_repairable_tool.png
/usr/share/minetest/games/devtest/mods/unittests/textures/unittests_steel_ingot.png
/usr/share/minetest/games/devtest/mods/unittests/textures/unittests_stick.png
/usr/share/minetest/games/devtest/mods/unittests/textures/unittests_torch.png
/usr/share/minetest/games/devtest/mods/unittests/textures/unittests_unrepairable_tool.png
/usr/share/minetest/games/devtest/mods/util_commands/init.lua
/usr/share/minetest/games/devtest/mods/util_commands/mod.conf
/usr/share/minetest/games/devtest/screenshot.png
/usr/share/minetest/games/devtest/settingtypes.txt
/usr/share/minetest/textures/base/pack/air.png
/usr/share/minetest/textures/base/pack/aux_btn.png
/usr/share/minetest/textures/base/pack/blank.png
/usr/share/minetest/textures/base/pack/bubble.png
/usr/share/minetest/textures/base/pack/bubble_gone.png
/usr/share/minetest/textures/base/pack/camera_btn.png
/usr/share/minetest/textures/base/pack/cdb_add.png
/usr/share/minetest/textures/base/pack/cdb_clear.png
/usr/share/minetest/textures/base/pack/cdb_downloading.png
/usr/share/minetest/textures/base/pack/cdb_queued.png
/usr/share/minetest/textures/base/pack/cdb_update.png
/usr/share/minetest/textures/base/pack/cdb_viewonline.png
/usr/share/minetest/textures/base/pack/chat_btn.png
/usr/share/minetest/textures/base/pack/chat_hide_btn.png
/usr/share/minetest/textures/base/pack/chat_show_btn.png
/usr/share/minetest/textures/base/pack/checkbox_16.png
/usr/share/minetest/textures/base/pack/checkbox_32.png
/usr/share/minetest/textures/base/pack/checkbox_64.png
/usr/share/minetest/textures/base/pack/clear.png
/usr/share/minetest/textures/base/pack/crack_anylength.png
/usr/share/minetest/textures/base/pack/debug_btn.png
/usr/share/minetest/textures/base/pack/down.png
/usr/share/minetest/textures/base/pack/drop_btn.png
/usr/share/minetest/textures/base/pack/end_icon.png
/usr/share/minetest/textures/base/pack/error_screenshot.png
/usr/share/minetest/textures/base/pack/fast_btn.png
/usr/share/minetest/textures/base/pack/fly_btn.png
/usr/share/minetest/textures/base/pack/gear_icon.png
/usr/share/minetest/textures/base/pack/halo.png
/usr/share/minetest/textures/base/pack/heart.png
/usr/share/minetest/textures/base/pack/heart_gone.png
/usr/share/minetest/textures/base/pack/ignore.png
/usr/share/minetest/textures/base/pack/inventory_btn.png
/usr/share/minetest/textures/base/pack/joystick_bg.png
/usr/share/minetest/textures/base/pack/joystick_center.png
/usr/share/minetest/textures/base/pack/joystick_off.png
/usr/share/minetest/textures/base/pack/jump_btn.png
/usr/share/minetest/textures/base/pack/loading_screenshot.png
/usr/share/minetest/textures/base/pack/logo.png
/usr/share/minetest/textures/base/pack/menu_bg.png
/usr/share/minetest/textures/base/pack/menu_header.png
/usr/share/minetest/textures/base/pack/minimap_btn.png
/usr/share/minetest/textures/base/pack/minimap_mask_round.png
/usr/share/minetest/textures/base/pack/minimap_mask_square.png
/usr/share/minetest/textures/base/pack/minimap_overlay_round.png
/usr/share/minetest/textures/base/pack/minimap_overlay_square.png
/usr/share/minetest/textures/base/pack/next_icon.png
/usr/share/minetest/textures/base/pack/no_screenshot.png
/usr/share/minetest/textures/base/pack/no_texture_airlike.png
/usr/share/minetest/textures/base/pack/noclip_btn.png
/usr/share/minetest/textures/base/pack/object_marker_red.png
/usr/share/minetest/textures/base/pack/player.png
/usr/share/minetest/textures/base/pack/player_back.png
/usr/share/minetest/textures/base/pack/player_marker.png
/usr/share/minetest/textures/base/pack/plus.png
/usr/share/minetest/textures/base/pack/prev_icon.png
/usr/share/minetest/textures/base/pack/progress_bar.png
/usr/share/minetest/textures/base/pack/progress_bar_bg.png
/usr/share/minetest/textures/base/pack/rangeview_btn.png
/usr/share/minetest/textures/base/pack/rare_controls.png
/usr/share/minetest/textures/base/pack/refresh.png
/usr/share/minetest/textures/base/pack/search.png
/usr/share/minetest/textures/base/pack/server_flags_creative.png
/usr/share/minetest/textures/base/pack/server_flags_damage.png
/usr/share/minetest/textures/base/pack/server_flags_favorite.png
/usr/share/minetest/textures/base/pack/server_flags_pvp.png
/usr/share/minetest/textures/base/pack/server_ping_1.png
/usr/share/minetest/textures/base/pack/server_ping_2.png
/usr/share/minetest/textures/base/pack/server_ping_3.png
/usr/share/minetest/textures/base/pack/server_ping_4.png
/usr/share/minetest/textures/base/pack/smoke_puff.png
/usr/share/minetest/textures/base/pack/start_icon.png
/usr/share/minetest/textures/base/pack/sunrisebg.png
/usr/share/minetest/textures/base/pack/unknown_item.png
/usr/share/minetest/textures/base/pack/unknown_node.png
/usr/share/minetest/textures/base/pack/unknown_object.png
/usr/share/minetest/textures/base/pack/wieldhand.png
/usr/share/minetest/textures/base/pack/zoom.png

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/minetest/*

%files extras
%defattr(-,root,root,-)
/usr/bin/minetestserver
/usr/share/minetest/builtin/async/init.lua
/usr/share/minetest/builtin/client/chatcommands.lua
/usr/share/minetest/builtin/client/death_formspec.lua
/usr/share/minetest/builtin/client/init.lua
/usr/share/minetest/builtin/client/register.lua
/usr/share/minetest/builtin/common/after.lua
/usr/share/minetest/builtin/common/chatcommands.lua
/usr/share/minetest/builtin/common/filterlist.lua
/usr/share/minetest/builtin/common/information_formspecs.lua
/usr/share/minetest/builtin/common/misc_helpers.lua
/usr/share/minetest/builtin/common/serialize.lua
/usr/share/minetest/builtin/common/strict.lua
/usr/share/minetest/builtin/common/vector.lua
/usr/share/minetest/builtin/fstk/buttonbar.lua
/usr/share/minetest/builtin/fstk/dialog.lua
/usr/share/minetest/builtin/fstk/tabview.lua
/usr/share/minetest/builtin/fstk/ui.lua
/usr/share/minetest/builtin/game/auth.lua
/usr/share/minetest/builtin/game/chat.lua
/usr/share/minetest/builtin/game/constants.lua
/usr/share/minetest/builtin/game/deprecated.lua
/usr/share/minetest/builtin/game/detached_inventory.lua
/usr/share/minetest/builtin/game/falling.lua
/usr/share/minetest/builtin/game/features.lua
/usr/share/minetest/builtin/game/forceloading.lua
/usr/share/minetest/builtin/game/init.lua
/usr/share/minetest/builtin/game/item.lua
/usr/share/minetest/builtin/game/item_entity.lua
/usr/share/minetest/builtin/game/knockback.lua
/usr/share/minetest/builtin/game/misc.lua
/usr/share/minetest/builtin/game/privileges.lua
/usr/share/minetest/builtin/game/register.lua
/usr/share/minetest/builtin/game/statbars.lua
/usr/share/minetest/builtin/game/static_spawn.lua
/usr/share/minetest/builtin/game/voxelarea.lua
/usr/share/minetest/builtin/init.lua
/usr/share/minetest/builtin/mainmenu/common.lua
/usr/share/minetest/builtin/mainmenu/dlg_config_world.lua
/usr/share/minetest/builtin/mainmenu/dlg_contentstore.lua
/usr/share/minetest/builtin/mainmenu/dlg_create_world.lua
/usr/share/minetest/builtin/mainmenu/dlg_delete_content.lua
/usr/share/minetest/builtin/mainmenu/dlg_delete_world.lua
/usr/share/minetest/builtin/mainmenu/dlg_rename_modpack.lua
/usr/share/minetest/builtin/mainmenu/dlg_settings_advanced.lua
/usr/share/minetest/builtin/mainmenu/generate_from_settingtypes.lua
/usr/share/minetest/builtin/mainmenu/init.lua
/usr/share/minetest/builtin/mainmenu/pkgmgr.lua
/usr/share/minetest/builtin/mainmenu/tab_content.lua
/usr/share/minetest/builtin/mainmenu/tab_credits.lua
/usr/share/minetest/builtin/mainmenu/tab_local.lua
/usr/share/minetest/builtin/mainmenu/tab_online.lua
/usr/share/minetest/builtin/mainmenu/tab_settings.lua
/usr/share/minetest/builtin/mainmenu/textures.lua
/usr/share/minetest/builtin/profiler/init.lua
/usr/share/minetest/builtin/profiler/instrumentation.lua
/usr/share/minetest/builtin/profiler/reporter.lua
/usr/share/minetest/builtin/profiler/sampling.lua
/usr/share/minetest/builtin/settingtypes.txt

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/minetest/109a1b93b80352920797150a7f7adf4cf70ef40e
/usr/share/package-licenses/minetest/2b1b42e96714bc36f7bee9210a5e69e2586f7ee3
/usr/share/package-licenses/minetest/a6efc4d11f332f4843bc25b557c6bf3e5ef51458
/usr/share/package-licenses/minetest/b1b13828a3a2be603b24a38d3948c7811d85f851
/usr/share/package-licenses/minetest/b6c8486ea0f9b01549a4a9fd19216d6e8480f8d6

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man6/minetest.6
/usr/share/man/man6/minetestserver.6

%files locales -f minetest.lang
%defattr(-,root,root,-)

