#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v19
# autospec commit: 6a4b23bb3e69
#
Name     : minetest
Version  : 5.9.1
Release  : 50
URL      : https://github.com/minetest/minetest/archive/5.9.1/minetest-5.9.1.tar.gz
Source0  : https://github.com/minetest/minetest/archive/5.9.1/minetest-5.9.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 CC-BY-SA-3.0 LGPL-2.1 LGPL-2.1+ MIT Zlib
Requires: minetest-bin = %{version}-%{release}
Requires: minetest-data = %{version}-%{release}
Requires: minetest-license = %{version}-%{release}
Requires: minetest-locales = %{version}-%{release}
Requires: minetest-man = %{version}-%{release}
BuildRequires : LuaJIT-dev
BuildRequires : buildreq-cmake
BuildRequires : bzip2-dev
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : glibc-dev
BuildRequires : gmp-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libogg-dev
BuildRequires : libpng-dev
BuildRequires : libspatialindex-dev
BuildRequires : libvorbis-dev
BuildRequires : lua-dev
BuildRequires : mesa-dev
BuildRequires : ncurses-dev
BuildRequires : openal-soft-dev
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(x11)
BuildRequires : postgresql-dev
BuildRequires : sqlite-autoconf-dev
BuildRequires : zlib-dev
BuildRequires : zstd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Minetest
========
![Build Status](https://github.com/minetest/minetest/workflows/build/badge.svg)
[![Translation status](https://hosted.weblate.org/widgets/minetest/-/svg-badge.svg)](https://hosted.weblate.org/engage/minetest/?utm_source=widget)
[![License](https://img.shields.io/badge/license-LGPLv2.1%2B-blue.svg)](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html)

%package bin
Summary: bin components for the minetest package.
Group: Binaries
Requires: minetest-data = %{version}-%{release}
Requires: minetest-license = %{version}-%{release}

%description bin
bin components for the minetest package.


%package data
Summary: data components for the minetest package.
Group: Data

%description data
data components for the minetest package.


%package doc
Summary: doc components for the minetest package.
Group: Documentation
Requires: minetest-man = %{version}-%{release}

%description doc
doc components for the minetest package.


%package extras
Summary: extras components for the minetest package.
Group: Default

%description extras
extras components for the minetest package.


%package license
Summary: license components for the minetest package.
Group: Default

%description license
license components for the minetest package.


%package locales
Summary: locales components for the minetest package.
Group: Default

%description locales
locales components for the minetest package.


%package man
Summary: man components for the minetest package.
Group: Default

%description man
man components for the minetest package.


%prep
%setup -q -n minetest-5.9.1
cd %{_builddir}/minetest-5.9.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726591502
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DBUILD_CLIENT=1 \
-DBUILD_SERVER=1 \
-DENABLE_FREETYPE=1 \
-DBUILD_SHARED_LIBS=0  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1726591502
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/minetest
cp %{_builddir}/minetest-%{version}/COPYING.LESSER %{buildroot}/usr/share/package-licenses/minetest/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/minetest-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/minetest/5abd99a8b5b89e83f8db0ea4b969f27823b85c67 || :
cp %{_builddir}/minetest-%{version}/fonts/Arimo-LICENSE.txt %{buildroot}/usr/share/package-licenses/minetest/b1b13828a3a2be603b24a38d3948c7811d85f851 || :
cp %{_builddir}/minetest-%{version}/fonts/Cousine-LICENSE.txt %{buildroot}/usr/share/package-licenses/minetest/2b1b42e96714bc36f7bee9210a5e69e2586f7ee3 || :
cp %{_builddir}/minetest-%{version}/fonts/DroidSansFallbackFull-LICENSE.txt %{buildroot}/usr/share/package-licenses/minetest/b6c8486ea0f9b01549a4a9fd19216d6e8480f8d6 || :
cp %{_builddir}/minetest-%{version}/games/devtest/mods/testformspec/LICENSE.txt %{buildroot}/usr/share/package-licenses/minetest/109a1b93b80352920797150a7f7adf4cf70ef40e || :
cp %{_builddir}/minetest-%{version}/irr/LICENSE %{buildroot}/usr/share/package-licenses/minetest/72d36e748c1f8e0a697f46999ea796007f30b868 || :
cp %{_builddir}/minetest-%{version}/lib/lua/COPYRIGHT %{buildroot}/usr/share/package-licenses/minetest/a6efc4d11f332f4843bc25b557c6bf3e5ef51458 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang minetest

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/minetest

%files data
%defattr(-,root,root,-)
/usr/share/applications/net.minetest.minetest.desktop
/usr/share/icons/hicolor/128x128/apps/minetest.png
/usr/share/icons/hicolor/scalable/apps/minetest.svg
/usr/share/metainfo/net.minetest.minetest.metainfo.xml
/usr/share/minetest/builtin/common/item_s.lua
/usr/share/minetest/builtin/common/metatable.lua
/usr/share/minetest/builtin/common/register.lua
/usr/share/minetest/builtin/common/tests/after_spec.lua
/usr/share/minetest/builtin/emerge/env.lua
/usr/share/minetest/builtin/emerge/init.lua
/usr/share/minetest/builtin/emerge/register.lua
/usr/share/minetest/builtin/game/hud.lua
/usr/share/minetest/builtin/game/tests/test_moveaction.lua
/usr/share/minetest/builtin/locale/__builtin.eo.tr
/usr/share/minetest/builtin/locale/__builtin.fr.tr
/usr/share/minetest/builtin/locale/__builtin.id.tr
/usr/share/minetest/builtin/locale/__builtin.ms.tr
/usr/share/minetest/builtin/locale/__builtin.pt_BR.tr
/usr/share/minetest/builtin/locale/__builtin.ru.tr
/usr/share/minetest/builtin/mainmenu/content/contentdb.lua
/usr/share/minetest/builtin/mainmenu/content/dlg_contentdb.lua
/usr/share/minetest/builtin/mainmenu/content/dlg_install.lua
/usr/share/minetest/builtin/mainmenu/content/dlg_overwrite.lua
/usr/share/minetest/builtin/mainmenu/content/init.lua
/usr/share/minetest/builtin/mainmenu/content/pkgmgr.lua
/usr/share/minetest/builtin/mainmenu/content/screenshots.lua
/usr/share/minetest/builtin/mainmenu/content/tests/pkgmgr_spec.lua
/usr/share/minetest/builtin/mainmenu/content/update_detector.lua
/usr/share/minetest/builtin/mainmenu/dlg_reinstall_mtg.lua
/usr/share/minetest/builtin/mainmenu/settings/components.lua
/usr/share/minetest/builtin/mainmenu/settings/dlg_change_mapgen_flags.lua
/usr/share/minetest/builtin/mainmenu/settings/dlg_settings.lua
/usr/share/minetest/builtin/mainmenu/settings/generate_from_settingtypes.lua
/usr/share/minetest/builtin/mainmenu/settings/init.lua
/usr/share/minetest/builtin/mainmenu/settings/settingtypes.lua
/usr/share/minetest/builtin/mainmenu/settings/shadows_component.lua
/usr/share/minetest/client/shaders/3d_interlaced_merge/opengl_fragment.glsl
/usr/share/minetest/client/shaders/3d_interlaced_merge/opengl_vertex.glsl
/usr/share/minetest/client/shaders/Irrlicht/OneTextureBlend.fsh
/usr/share/minetest/client/shaders/Irrlicht/Renderer2D.fsh
/usr/share/minetest/client/shaders/Irrlicht/Renderer2D.vsh
/usr/share/minetest/client/shaders/Irrlicht/Renderer2D_noTex.fsh
/usr/share/minetest/client/shaders/Irrlicht/Solid.fsh
/usr/share/minetest/client/shaders/Irrlicht/Solid.vsh
/usr/share/minetest/client/shaders/Irrlicht/TransparentAlphaChannel.fsh
/usr/share/minetest/client/shaders/Irrlicht/TransparentAlphaChannelRef.fsh
/usr/share/minetest/client/shaders/Irrlicht/TransparentVertexAlpha.fsh
/usr/share/minetest/client/shaders/bloom_downsample/opengl_fragment.glsl
/usr/share/minetest/client/shaders/bloom_downsample/opengl_vertex.glsl
/usr/share/minetest/client/shaders/bloom_upsample/opengl_fragment.glsl
/usr/share/minetest/client/shaders/bloom_upsample/opengl_vertex.glsl
/usr/share/minetest/client/shaders/blur_h/opengl_fragment.glsl
/usr/share/minetest/client/shaders/blur_h/opengl_vertex.glsl
/usr/share/minetest/client/shaders/blur_v/opengl_fragment.glsl
/usr/share/minetest/client/shaders/blur_v/opengl_vertex.glsl
/usr/share/minetest/client/shaders/cloud_shader/opengl_fragment.glsl
/usr/share/minetest/client/shaders/cloud_shader/opengl_vertex.glsl
/usr/share/minetest/client/shaders/default_shader/opengl_fragment.glsl
/usr/share/minetest/client/shaders/default_shader/opengl_vertex.glsl
/usr/share/minetest/client/shaders/extract_bloom/opengl_fragment.glsl
/usr/share/minetest/client/shaders/extract_bloom/opengl_vertex.glsl
/usr/share/minetest/client/shaders/fxaa/opengl_fragment.glsl
/usr/share/minetest/client/shaders/fxaa/opengl_vertex.glsl
/usr/share/minetest/client/shaders/minimap_shader/opengl_fragment.glsl
/usr/share/minetest/client/shaders/minimap_shader/opengl_vertex.glsl
/usr/share/minetest/client/shaders/nodes_shader/opengl_fragment.glsl
/usr/share/minetest/client/shaders/nodes_shader/opengl_vertex.glsl
/usr/share/minetest/client/shaders/object_shader/opengl_fragment.glsl
/usr/share/minetest/client/shaders/object_shader/opengl_vertex.glsl
/usr/share/minetest/client/shaders/second_stage/opengl_fragment.glsl
/usr/share/minetest/client/shaders/second_stage/opengl_vertex.glsl
/usr/share/minetest/client/shaders/selection_shader/opengl_fragment.glsl
/usr/share/minetest/client/shaders/selection_shader/opengl_vertex.glsl
/usr/share/minetest/client/shaders/shadow_shaders/pass1_fragment.glsl
/usr/share/minetest/client/shaders/shadow_shaders/pass1_trans_fragment.glsl
/usr/share/minetest/client/shaders/shadow_shaders/pass1_trans_vertex.glsl
/usr/share/minetest/client/shaders/shadow_shaders/pass1_vertex.glsl
/usr/share/minetest/client/shaders/shadow_shaders/pass2_fragment.glsl
/usr/share/minetest/client/shaders/shadow_shaders/pass2_vertex.glsl
/usr/share/minetest/client/shaders/stars_shader/opengl_fragment.glsl
/usr/share/minetest/client/shaders/stars_shader/opengl_vertex.glsl
/usr/share/minetest/client/shaders/update_exposure/opengl_fragment.glsl
/usr/share/minetest/client/shaders/update_exposure/opengl_vertex.glsl
/usr/share/minetest/client/shaders/volumetric_light/opengl_fragment.glsl
/usr/share/minetest/client/shaders/volumetric_light/opengl_vertex.glsl
/usr/share/minetest/fonts/Arimo-Bold.ttf
/usr/share/minetest/fonts/Arimo-BoldItalic.ttf
/usr/share/minetest/fonts/Arimo-Italic.ttf
/usr/share/minetest/fonts/Arimo-LICENSE.txt
/usr/share/minetest/fonts/Arimo-Regular.ttf
/usr/share/minetest/fonts/Cousine-Bold.ttf
/usr/share/minetest/fonts/Cousine-BoldItalic.ttf
/usr/share/minetest/fonts/Cousine-Italic.ttf
/usr/share/minetest/fonts/Cousine-LICENSE.txt
/usr/share/minetest/fonts/Cousine-Regular.ttf
/usr/share/minetest/fonts/DroidSansFallbackFull-LICENSE.txt
/usr/share/minetest/fonts/DroidSansFallbackFull.ttf
/usr/share/minetest/textures/base/pack/air.png
/usr/share/minetest/textures/base/pack/aux1_btn.png
/usr/share/minetest/textures/base/pack/blank.png
/usr/share/minetest/textures/base/pack/bubble.png
/usr/share/minetest/textures/base/pack/bubble_gone.png
/usr/share/minetest/textures/base/pack/camera_btn.png
/usr/share/minetest/textures/base/pack/cdb_add.png
/usr/share/minetest/textures/base/pack/cdb_clear.png
/usr/share/minetest/textures/base/pack/cdb_downloading.png
/usr/share/minetest/textures/base/pack/cdb_queued.png
/usr/share/minetest/textures/base/pack/cdb_update.png
/usr/share/minetest/textures/base/pack/cdb_update_cropped.png
/usr/share/minetest/textures/base/pack/cdb_viewonline.png
/usr/share/minetest/textures/base/pack/chat_btn.png
/usr/share/minetest/textures/base/pack/chat_hide_btn.png
/usr/share/minetest/textures/base/pack/chat_show_btn.png
/usr/share/minetest/textures/base/pack/checkbox_16.png
/usr/share/minetest/textures/base/pack/checkbox_32.png
/usr/share/minetest/textures/base/pack/checkbox_64.png
/usr/share/minetest/textures/base/pack/clear.png
/usr/share/minetest/textures/base/pack/crack_anylength.png
/usr/share/minetest/textures/base/pack/debug_btn.png
/usr/share/minetest/textures/base/pack/down.png
/usr/share/minetest/textures/base/pack/drop_btn.png
/usr/share/minetest/textures/base/pack/end_icon.png
/usr/share/minetest/textures/base/pack/error_icon_orange.png
/usr/share/minetest/textures/base/pack/error_icon_red.png
/usr/share/minetest/textures/base/pack/error_screenshot.png
/usr/share/minetest/textures/base/pack/exit_btn.png
/usr/share/minetest/textures/base/pack/fast_btn.png
/usr/share/minetest/textures/base/pack/fly_btn.png
/usr/share/minetest/textures/base/pack/gear_icon.png
/usr/share/minetest/textures/base/pack/halo.png
/usr/share/minetest/textures/base/pack/heart.png
/usr/share/minetest/textures/base/pack/heart_gone.png
/usr/share/minetest/textures/base/pack/ignore.png
/usr/share/minetest/textures/base/pack/inventory_btn.png
/usr/share/minetest/textures/base/pack/joystick_bg.png
/usr/share/minetest/textures/base/pack/joystick_center.png
/usr/share/minetest/textures/base/pack/joystick_off.png
/usr/share/minetest/textures/base/pack/jump_btn.png
/usr/share/minetest/textures/base/pack/loading_screenshot.png
/usr/share/minetest/textures/base/pack/logo.png
/usr/share/minetest/textures/base/pack/menu_bg.png
/usr/share/minetest/textures/base/pack/menu_header.png
/usr/share/minetest/textures/base/pack/minimap_btn.png
/usr/share/minetest/textures/base/pack/minimap_mask_round.png
/usr/share/minetest/textures/base/pack/minimap_mask_square.png
/usr/share/minetest/textures/base/pack/minimap_overlay_round.png
/usr/share/minetest/textures/base/pack/minimap_overlay_square.png
/usr/share/minetest/textures/base/pack/next_icon.png
/usr/share/minetest/textures/base/pack/no_screenshot.png
/usr/share/minetest/textures/base/pack/no_texture.png
/usr/share/minetest/textures/base/pack/no_texture_airlike.png
/usr/share/minetest/textures/base/pack/noclip_btn.png
/usr/share/minetest/textures/base/pack/object_marker_red.png
/usr/share/minetest/textures/base/pack/player.png
/usr/share/minetest/textures/base/pack/player_back.png
/usr/share/minetest/textures/base/pack/player_marker.png
/usr/share/minetest/textures/base/pack/plus.png
/usr/share/minetest/textures/base/pack/prev_icon.png
/usr/share/minetest/textures/base/pack/progress_bar.png
/usr/share/minetest/textures/base/pack/progress_bar_bg.png
/usr/share/minetest/textures/base/pack/rangeview_btn.png
/usr/share/minetest/textures/base/pack/rare_controls.png
/usr/share/minetest/textures/base/pack/refresh.png
/usr/share/minetest/textures/base/pack/search.png
/usr/share/minetest/textures/base/pack/server_favorite.png
/usr/share/minetest/textures/base/pack/server_favorite_delete.png
/usr/share/minetest/textures/base/pack/server_flags_creative.png
/usr/share/minetest/textures/base/pack/server_flags_damage.png
/usr/share/minetest/textures/base/pack/server_flags_pvp.png
/usr/share/minetest/textures/base/pack/server_incompatible.png
/usr/share/minetest/textures/base/pack/server_ping_1.png
/usr/share/minetest/textures/base/pack/server_ping_2.png
/usr/share/minetest/textures/base/pack/server_ping_3.png
/usr/share/minetest/textures/base/pack/server_ping_4.png
/usr/share/minetest/textures/base/pack/server_public.png
/usr/share/minetest/textures/base/pack/settings_btn.png
/usr/share/minetest/textures/base/pack/settings_info.png
/usr/share/minetest/textures/base/pack/settings_reset.png
/usr/share/minetest/textures/base/pack/smoke_puff.png
/usr/share/minetest/textures/base/pack/start_icon.png
/usr/share/minetest/textures/base/pack/sunrisebg.png
/usr/share/minetest/textures/base/pack/unknown_item.png
/usr/share/minetest/textures/base/pack/unknown_node.png
/usr/share/minetest/textures/base/pack/unknown_object.png
/usr/share/minetest/textures/base/pack/wieldhand.png
/usr/share/minetest/textures/base/pack/zoom.png

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/minetest/*

%files extras
%defattr(-,root,root,-)
/usr/bin/minetestserver
/usr/share/minetest/builtin/async/game.lua
/usr/share/minetest/builtin/async/mainmenu.lua
/usr/share/minetest/builtin/client/chatcommands.lua
/usr/share/minetest/builtin/client/death_formspec.lua
/usr/share/minetest/builtin/client/init.lua
/usr/share/minetest/builtin/client/misc.lua
/usr/share/minetest/builtin/client/register.lua
/usr/share/minetest/builtin/common/after.lua
/usr/share/minetest/builtin/common/chatcommands.lua
/usr/share/minetest/builtin/common/filterlist.lua
/usr/share/minetest/builtin/common/information_formspecs.lua
/usr/share/minetest/builtin/common/misc_helpers.lua
/usr/share/minetest/builtin/common/mod_storage.lua
/usr/share/minetest/builtin/common/serialize.lua
/usr/share/minetest/builtin/common/strict.lua
/usr/share/minetest/builtin/common/tests/misc_helpers_spec.lua
/usr/share/minetest/builtin/common/tests/serialize_spec.lua
/usr/share/minetest/builtin/common/tests/vector_spec.lua
/usr/share/minetest/builtin/common/vector.lua
/usr/share/minetest/builtin/fstk/buttonbar.lua
/usr/share/minetest/builtin/fstk/dialog.lua
/usr/share/minetest/builtin/fstk/tabview.lua
/usr/share/minetest/builtin/fstk/ui.lua
/usr/share/minetest/builtin/game/async.lua
/usr/share/minetest/builtin/game/auth.lua
/usr/share/minetest/builtin/game/chat.lua
/usr/share/minetest/builtin/game/constants.lua
/usr/share/minetest/builtin/game/deprecated.lua
/usr/share/minetest/builtin/game/detached_inventory.lua
/usr/share/minetest/builtin/game/falling.lua
/usr/share/minetest/builtin/game/features.lua
/usr/share/minetest/builtin/game/forceloading.lua
/usr/share/minetest/builtin/game/init.lua
/usr/share/minetest/builtin/game/item.lua
/usr/share/minetest/builtin/game/item_entity.lua
/usr/share/minetest/builtin/game/knockback.lua
/usr/share/minetest/builtin/game/misc.lua
/usr/share/minetest/builtin/game/misc_s.lua
/usr/share/minetest/builtin/game/privileges.lua
/usr/share/minetest/builtin/game/register.lua
/usr/share/minetest/builtin/game/static_spawn.lua
/usr/share/minetest/builtin/game/voxelarea.lua
/usr/share/minetest/builtin/init.lua
/usr/share/minetest/builtin/locale/__builtin.de.tr
/usr/share/minetest/builtin/locale/__builtin.it.tr
/usr/share/minetest/builtin/locale/template.txt
/usr/share/minetest/builtin/mainmenu/async_event.lua
/usr/share/minetest/builtin/mainmenu/common.lua
/usr/share/minetest/builtin/mainmenu/dlg_config_world.lua
/usr/share/minetest/builtin/mainmenu/dlg_create_world.lua
/usr/share/minetest/builtin/mainmenu/dlg_delete_content.lua
/usr/share/minetest/builtin/mainmenu/dlg_delete_world.lua
/usr/share/minetest/builtin/mainmenu/dlg_register.lua
/usr/share/minetest/builtin/mainmenu/dlg_rename_modpack.lua
/usr/share/minetest/builtin/mainmenu/dlg_version_info.lua
/usr/share/minetest/builtin/mainmenu/game_theme.lua
/usr/share/minetest/builtin/mainmenu/init.lua
/usr/share/minetest/builtin/mainmenu/serverlistmgr.lua
/usr/share/minetest/builtin/mainmenu/tab_about.lua
/usr/share/minetest/builtin/mainmenu/tab_content.lua
/usr/share/minetest/builtin/mainmenu/tab_local.lua
/usr/share/minetest/builtin/mainmenu/tab_online.lua
/usr/share/minetest/builtin/mainmenu/tests/favorites_wellformed.txt
/usr/share/minetest/builtin/mainmenu/tests/serverlistmgr_spec.lua
/usr/share/minetest/builtin/profiler/init.lua
/usr/share/minetest/builtin/profiler/instrumentation.lua
/usr/share/minetest/builtin/profiler/reporter.lua
/usr/share/minetest/builtin/profiler/sampling.lua
/usr/share/minetest/builtin/settingtypes.txt

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/minetest/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/minetest/109a1b93b80352920797150a7f7adf4cf70ef40e
/usr/share/package-licenses/minetest/2b1b42e96714bc36f7bee9210a5e69e2586f7ee3
/usr/share/package-licenses/minetest/5abd99a8b5b89e83f8db0ea4b969f27823b85c67
/usr/share/package-licenses/minetest/72d36e748c1f8e0a697f46999ea796007f30b868
/usr/share/package-licenses/minetest/a6efc4d11f332f4843bc25b557c6bf3e5ef51458
/usr/share/package-licenses/minetest/b1b13828a3a2be603b24a38d3948c7811d85f851
/usr/share/package-licenses/minetest/b6c8486ea0f9b01549a4a9fd19216d6e8480f8d6

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man6/minetest.6
/usr/share/man/man6/minetestserver.6

%files locales -f minetest.lang
%defattr(-,root,root,-)

